dist: xenial
sudo: true
language: go

go:
  - 1.12.5

go_import_path: github.com/jetstack/cert-manager

install: true

notifications:
  email: false

env:
  - BAZEL_VERSION=0.28.1

services:
  - docker

before_install:
  - |
    URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io

script:
  - make verify

branches:
  only:
  - privateacm
  - /^v.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      DOCKER_TAG=$TRAVIS_TAG bazel run //hack/release --
      --repo-root "$TRAVIS_BUILD_DIR"
      --images
      --images.export
      --images.components=controller,webhook
      --publish
      --app-version="$TRAVIS_TAG"
      --docker-repo="quay.io/dreamteam"
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
